```{r, setup, include=FALSE}
library(tidyverse)
```

```{r}
diversity <- read.csv("logs/diversity_0.csv")
colnames(diversity) <- c("generation", "diversity")
fitness <- read.csv("logs/fitness_0.csv")
colnames(fitness) <- c("generation", "fitness")
population <- read.csv("logs/population_0.csv")
colnames(population) <- c("generation", "individual", "gene_index", "gene_value")
```

```{r}
first_gene <- population$gene_value[population$generation == 50 & population$gene_index == 0]
hist(first_gene, breaks=19)
shapiro.test(first_gene)
```

```{r}
library("entropy")
```

```{r}
first_gene
z = discretize(first_gene, numBins = 20)
entropy(z)
```


```{r}
truncated_diversity <- diversity %>% filter(generation > 100)
ggplot(truncated_diversity, aes(x = generation, y = diversity)) + geom_line() + scale_y_continuous(trans='log10')
```

```{r}
truncated_fitness <- fitness %>% filter(generation > 100)
ggplot(truncated_fitness, aes(x = generation, y = fitness)) + geom_line() + scale_y_continuous(trans='log10')
```